jobs:
  - name: Check out
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '21'

  - name: Make gradlew executable (Unix/macOS only)
    if: runner.os != 'Windows'
    run: chmod +x ./gradlew

  - name: Build (Linux/macOS)
    if: runner.os != 'Windows'
    shell: bash
    run: |
      echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
      echo 'org.gradle.caching=true' >> gradle.properties
      echo 'org.gradle.parallel=true' >> gradle.properties
      ./gradlew assemble

  - name: Build (Windows)
    if: runner.os == 'Windows'
    run: .\gradlew.bat assemble
    shell: pwsh

  - name: Upload build artifact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ matrix.os }}-artifact
      path: app/build/outputs
